version: "3"

services:
  redis:
    image: 'redis:alpine'
    volumes:
      - 'redis:/data'
    env_file:
      - foodgroup.env
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
  node:
    build: ./backend
    depends_on:
      - sql
    env_file:
      # Make sure to update this to match your project.
      - foodgroup.env
    environment:
      - MYSQL_HOST=sql
    ports:
      - 8080:4200
    volumes:
      - ./backend/src:/home/node/app/src
      - ./backend/tsconfig.json:/home/node/app/tsconfig.json
  sql:
    build: ./sql
    # Make sure to update this to match your project.
    env_file:
      - foodgroup.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - compose-lesson:/var/lib/mysql
    ports:
      - 33006:3306
  app:
    build: frontend
    depends_on:
      - node
    #    For deploying to server use ports: - 80:80
    ports:
      - 80:80
volumes:
  compose-lesson:
    driver: local
  redis:
    driver: local